/*
 * generated by Xtext
 */
package com.blasedef.onpa.ui.contentassist

import com.blasedef.onpa.ui.contentassist.AbstractONPAProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ONPAProposalProvider extends AbstractONPAProposalProvider {
}
