/*
 * generated by Xtext
 */
package com.blasedef.onpa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.blasedef.onpa.ui.internal.ONPAActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ONPAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ONPAActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ONPAActivator.getInstance().getInjector(ONPAActivator.COM_BLASEDEF_ONPA_ONPA);
	}
	
}
